server:
  port: 3366

# Logger config
logging:
  config: classpath:log4j2.xml

spring:
  application:
    name: rq-microservice
  key-store: classpath:ssl/ydq.luqinghe.com.jks
  key-store-password: 5fa715dtzloz13
  key-store-type: JKS

file:
  path: http://cdn.arraylist.cn/ReleaseQuarantine.xlsx