spring:
  application:
    name: mybatisplus
  profiles:
    active: dev


server:
  port: 6604

# Logger config
logging:
  config: classpath:log4j2.xml

#mybatis-plus
mybatis-plus:
  global-config:
    db-config:
      id-type: AUTO
      field-strategy: not_empty
      table-underline: true
      db-type: mysql
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
  mapper-locations: classpath:/org/nh/**/*.xml
  configuration:
    # 这个配置会将执行的sql打印出来，在开发或测试的时候可以用
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

